package com.example.pizzeria;

public enum TipoIngrediente {

    CHAMPIÑON,JAMON_YORK,CHORIZO,ANCHOAS,OLIVAS,
    TOMATE_FRITO,ATUN,GAMBAS,MOZZARELLA,MIMOLE,EMMENTAL,ROQUEFORT,
    PIMIENTO_VERDE,HUEVO_BATIDO,CEBOLLA,PIÑA,DOBLE_DE_QUESO,
    NATA,BEICON,ESPIRALES_DE_VERDURA,SALSA_BARBACOA,TERNERA,
    CARNE_KEBAB,SALSA_KEBAB,CREMA_QUESO,POLLO,CEBOLLA_CARAMELIZADA,
    QUESO_RULO_DE_CABRA,CREMA_AGRIA,SALSA_GAUCHA,PATATAS_FRITAS,
    SALSA_ALIOLI,PULLED_CON_BARBACOA,MAIZ,SALSA_CHEDDAR,ALBAHACA,
    ACEITE_OLIVA,AJO,OREGANO,SALSA_PICANTE,ACEITUNAS,JAMON,CALABAZA
    ,TRUFA,ALCACHOFAS;

}
